import asyncio
import time
import json
from fastapi import FastAPI
from fastapi.responses import JSONResponse, StreamingResponse
import uvicorn

app = FastAPI(title="Universal Multi-Model Upstream Mock")

@app.post("/v1/chat/completions")
async def completions(payload: dict):
    model = payload.get("model", "gpt-4o")
    is_stream = payload.get("stream", False)

    # Simulated primary outage for failover testing
    if model == "gpt-4o-failing":
        return JSONResponse(
            status_code=503,
            content={"error": {"message": "Simulated primary model outage", "type": "server_error"}}
        )

    # Provider classification
    if "gemini" in model.lower():
        provider_name = "Google Vertex / Gemini"
    elif "claude" in model.lower():
        provider_name = "Anthropic"
    elif any(oss in model.lower() for oss in ["llama", "deepseek", "qwen", "mistral"]):
        provider_name = "Open-Source (vLLM / Groq)"
    else:
        provider_name = "OpenAI"

    if is_stream:
        async def event_generator():
            words = [f"[{provider_name}]", " Real-time", " inference", f" from {model}", " completed."]
            for i, word in enumerate(words):
                chunk = {
                    "id": f"chatcmpl-{int(time.time())}",
                    "object": "chat.completion.chunk",
                    "created": int(time.time()),
                    "model": model,
                    "choices": [{
                        "index": 0,
                        "delta": {"content": f" {word}"},
                        "finish_reason": "stop" if i == len(words) - 1 else None
                    }]
                }
                yield f"data: {json.dumps(chunk)}\n\n".encode("utf-8")
                await asyncio.sleep(0.03)
            yield b"data: [DONE]\n\n"

        return StreamingResponse(event_generator(), media_type="text/event-stream")

    return {
        "id": f"chatcmpl-{int(time.time())}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "message": {
                "role": "assistant",
                "content": f"Response generated by [{provider_name}] model: {model}."
            },
            "finish_reason": "stop"
        }],
        "usage": {
            "prompt_tokens": 18,
            "completion_tokens": 12,
            "total_tokens": 30
        }
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8001)
