apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: gateway-clickhouse
      port: 9000
      protocol: native
      database: ai_gateway
      username: default
      tlsSkipVerify: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: false
    url: http://host.docker.internal:9090
    jsonData:
      httpMethod: POST
    editable: true
